name: Build

on:
  push:
  schedule:
    - cron: "00 23 2 * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo docker build -t "cargoz/odoo-tester" .
      - name: Test
        run: |
          sudo docker run --rm "cargoz/odoo-tester"
      - name: Publish
        run: |
          sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" \
                            -p "${{ secrets.DOCKER_PASSWORD }}"
          sudo docker push "${GITHUB_REPOSITORY}"
